# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseURL = "https://justobjects.nl/"
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
## Next line hides the language selector
disableLanguages = ["pt", "ja"]

# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[redirects]]
  from = "/feed"
  to = "/index.xml"
  status = 200
  force = true

[[redirects]]
  from = "/feed/"
  to = "/index.xml"
  status = 200
  force = true
