# [[main]]
#  name = "Home"
#  url = ""
#  weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -109

[[main]]
  name = "Writings"
  identifier = "Writings"
  # url = "writings/"
  weight = -108
[[main]]
  parent = "Writings"
  name = "Blog"
  # url = "writings/blog/"
  # url = "blog/"
  url = "posts/"
[[main]]
  parent = "Writings"
  name = "Tweets"
  # url = "writings/tweets/"
  url = "tweets/"
[[main]]
  parent = "Writings"
  name = "Presentations"
  # url = "writings/presentations/"
  url = "presentations/"
[[main]]
  parent = "Writings"
  name = "Publications"
  # url = "writings/publications/"
  url = "publications/"

[[main]]
  name = "Projects"
  identifier = "Projects"
  url = "projects/"
  weight = -107
[[main]]
  parent = "Projects"
  name = "Overview"
  url = "projects/"
  weight = -99
[[main]]
  parent = "Projects"
  # name = "Heron Mapping Client →"
  name = "Heron Mapping Client"
  url = "http://heron-mc.org"
  weight = -98
[[main]]
  parent = "Projects"
  # name = "GeoHealthCheck – OGC GeoSpatial Web Service Monitoring →"
  name = "GeoHealthCheck – OGC GeoSpatial Web Service Monitoring"
  url = "https://geohealthcheck.org"
  weight = -97
[[main]]
  parent = "Projects"
  name = "Smart Emission – Open Sensor Web Platform"
  url = "http://data.smartemission.nl"
  weight = -96
[[main]]
  parent = "Projects"
  name = "Stetl – Streaming ETL"
  url = "http://stetl.org"
  weight = -95
[[main]]
  parent = "Projects"
  name = "NLExtract – Unlock Dutch Geodata"
  url = "http://nlextract.nl"
  weight = -94
[[main]]
  parent = "Projects"
  name = "INSPIRE FOSS – Free and Open Source for INSPIRE"
  url = "https://github.com/justb4/inspire-foss"
  weight = -93
[[main]]
  parent = "Projects"
  name = "7Scenes – create mobile games and tours"
  url = "http://7scenes.com"
  weight = -92
[[main]]
  parent = "Projects"
  name = "MapGlow – heatmaps via WMS"
  url = "https://github.com/justb4/mapglow"
  weight = -91
[[main]]
  parent = "Projects"
  name = "GeoSkating – map your inline skating tracks"
  url = "http://geoskating.com"
  weight = -90
[[main]]
  parent = "Projects"
  name = "GeoRambling – Just’s Multimedial GPS Hikes"
  url = "http://georambling.com"
  weight = -89
[[main]]
  parent = "Projects"
  name = "Pushlets – PubSub via HTTP"
  url = "http://pushlets.com"
  weight = -88
[[main]]
  parent = "Projects"
  name = "CowCatcher – Free Java Training Materials"
  url = "http://justobjects.org/cowcatcher"
  weight = -87

[[main]]
  name = "Products"
  identifier = "Products"
  url = "products/"
  weight = -102
[[main]]
  parent = "Products"
  name = "map5.nl"
  url = "map5/"
  weight = -99
[[main]]
  parent = "Products"
  name = "geoqos.com"
  url = "geoqos/"
  weight = -98

# [[main]]
#  name = "Archives"
#  url = "post/rich-content/"
#  weight = -106

# Submenus are done this way: parent -> identifier
# [[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -105
# [[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
# [[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/#"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
